services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5174:5173"
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

    depends_on:
      - backend

    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./backend:/app
      - backend-node-node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    restart: unless-stopped

  volumes:
    - backend-node-modules:
    - frontend-node-modules:
