name: Build & lint workflow
on: [push, pull_request]
run-name: Workflow created by ${{github.actor}} on ${{github.event_name}} event

jobs:
  check_lint:
    runs-on: ubuntu-latest
    steps:
      - name: action checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup super-linter
        uses: super-linter/super-linter@v8.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check-build:
    runs-on: ubuntu-latest
    steps:
      - name: action checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "20"
      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build
